In [6]:
from sklearn import datasets
import numpy as np
df=datasets.load_iris()
# X=df[:,]
X=df.data[:,[2,3]]
y=df.target

In [7]:
print("class label:,", np.unique(y))

class label:, [0 1 2]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

In [16]:
from sklearn.linear_model import Perceptron
ppn=Perceptron(eta0=0.1,random_state=1)
ppn.fit(X_train_std,y_train)

Perceptron(eta0=0.1, random_state=1)

In [20]:
y_pred=ppn.predict(X_test_std)
# print("missclassification: ",sum([1 if y_test[i]!=y_pred[i] else 0 for i in range(len(y_test)) ]))
print("missclassification: ",(y_pred!=y_test).sum())

missclassification:  1


In [22]:
from sklearn.linear_model import LogisticRegression
#There are much more efficient optimizer functions available rather that SGD, which can be specified using solver parameter
#Eg: lbfgs,saga,sag,liblinear etc
lr=LogisticRegression(C=100,solver='lbfgs',multi_class='ovr')# multi_class parameter set to one-vs-rest for more than 2 classes
lr.fit(X_train_std,y_train)

y_pred=lr.predict(X_test_std)
# print("missclassification: ",sum([1 if y_test[i]!=y_pred[i] else 0 for i in range(len(y_test)) ]))
print("missclassification: ",(y_pred!=y_test).sum())

missclassification:  1


In [31]:
#We can also predict the probability of a class
print(lr.predict_proba(X_test_std[:3]))
print(lr.predict_proba(X_test_std[:3]).argmax(axis=1))

[[3.81527885e-09 1.44792866e-01 8.55207131e-01]
 [8.34020679e-01 1.65979321e-01 3.25737138e-13]
 [8.48831425e-01 1.51168575e-01 2.62277619e-14]]
[2 0 0]


In [35]:
#Reshape method is used to add a new dimension to the array
print(lr.predict([X_test_std[0]]))
print(lr.predict(X_test_std[0].reshape(1,-1)))

[2]
[2]


In [41]:
np.random.seed(1)
X_xor=np.random.randn(200,2)
y_xor=np.logical_xor(X_xor[:,0]>0,X_xor[:,1]>0)
print(X_xor[1],y_xor[1])
y_xor=np.where(y_xor,1,0)
print(y_xor[1])

[-0.52817175 -1.07296862] False
0


In [44]:
from sklearn.svm import SVC
#The gamma parameter is used to see how lose or tight the decision boundaries are .
#Higher value of gamma makes the decision boundaries very tight and hence they are more prone to generalization errors.

svc=SVC(kernel="rbf",C=0.1,random_state=1,gamma=0.10)# Where C is the inverse of regularization factor
#Higher the value of C, lower the regularization parameter 
svc.fit(X_xor,y_xor)

SVC(C=0.1, gamma=0.1, random_state=1)

In [48]:
import scipy
res=scipy.stats.ttest_ind(a=[9, 11, 10,11,10,12, 9,11,12, 9, 10],b=[10, 13, 10, 13, 12, 9, 11, 12, 12, 12, 13],equal_var=True)
res

Ttest_indResult(statistic=-2.2164816032790386, pvalue=0.03841461541539729)

In [53]:
import pandas as pd 
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data',
    header=None
)
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
           dtype='int64')

In [63]:
from sklearn.preprocessing import LabelEncoder
X=df.loc[:,2:].values
y=df.loc[:,1]
le=LabelEncoder()
y=le.fit_transform(y)
le.transform

<bound method LabelEncoder.transform of LabelEncoder()>

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,stratify=y,test_size=0.2)

In [71]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
ss=StandardScaler()
pca=PCA(n_components=2)
lr=LogisticRegression(solver="lbfgs")
pipeline=make_pipeline(ss,pca,lr)
pipeline.fit(X_train,y_train)
y_pred=pipeline.predict(X_test)
test_acc=pipeline.score(X_test,y_test)
print("Score: ",test_acc)

Score:  0.9298245614035088


In [21]:
import pandas as pd
import numpy as np

boston_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
boston_df=pd.read_csv(boston_url)

In [22]:
boston_df.head(5)

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0           0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0   
1           1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0   
2           2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0   
3           3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0   
4           4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0   

     TAX  PTRATIO  LSTAT  MEDV  
0  296.0     15.3   4.98  24.0  
1  242.0     17.8   9.14  21.6  
2  242.0     17.8   4.03  34.7  
3  222.0     18.7   2.94  33.4  
4  222.0     18.7   5.33  36.2

In [5]:
import seaborn as sns 
sns.set_theme(style="whitegrid")


In [6]:
boston_df.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0           0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0   
1           1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0   
2           2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0   
3           3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0   
4           4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0   

     TAX  PTRATIO  LSTAT  MEDV  
0  296.0     15.3   4.98  24.0  
1  242.0     17.8   9.14  21.6  
2  242.0     17.8   4.03  34.7  
3  222.0     18.7   2.94  33.4  
4  222.0     18.7   5.33  36.2

In [17]:
import pandas as pd
columns = ['Overall Qual', 'Overall Cond', 'Gr Liv Area',
           'Central Air', 'Total Bsmt SF', 'SalePrice']
df=pd.read_csv("http://jse.amstat.org/v19n3/decock/AmesHousing.txt", sep="\t",
               usecols=columns)
df

Overall Qual  Overall Cond  Total Bsmt SF Central Air  Gr Liv Area  \
0                6             5         1080.0           Y         1656   
1                5             6          882.0           Y          896   
2                6             6         1329.0           Y         1329   
3                7             5         2110.0           Y         2110   
4                5             5          928.0           Y         1629   
...            ...           ...            ...         ...          ...   
2925             6             6         1003.0           Y         1003   
2926             5             5          864.0           Y          902   
2927             5             5          912.0           Y          970   
2928             5             5         1389.0           Y         1389   
2929             7             5          996.0           Y         2000   

      SalePrice  
0        215000  
1        105000  
2        172000  
3        244000  
4        189900  
...         ...  
2925     142500  
2926     131000  
2927     132000  
2928     170000  
2929     188000  

[2930 rows x 6 columns]

In [18]:
df["Central Air"]=df["Central Air"].map({"Y":1,"N":0})
df.head(2)

Overall Qual  Overall Cond  Total Bsmt SF  Central Air  Gr Liv Area  \
0             6             5         1080.0            1         1656   
1             5             6          882.0            1          896   

   SalePrice  
0     215000  
1     105000

In [19]:
df.isnull().sum()

Overall Qual     0
Overall Cond     0
Total Bsmt SF    1
Central Air      0
Gr Liv Area      0
SalePrice        0
dtype: int64

In [20]:
df.dropna(inplace=True,axis=0)
df.isnull().sum()

Overall Qual     0
Overall Cond     0
Total Bsmt SF    0
Central Air      0
Gr Liv Area      0
SalePrice        0
dtype: int64

In [15]:
df.shape

(2930, 5)